"""init schema

Revision ID: a1b38490cf06
Revises: 
Create Date: 2026-04-25 17:07:25.174039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1b38490cf06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('class_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_groups_id'), ['id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_id'), ['id'], unique=False)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_id'), ['id'], unique=False)

    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'start_time', 'end_time', name='uq_time_slot')
    )
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_slots_id'), ['id'], unique=False)

    op.create_table('course_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_requirements_id'), ['id'], unique=False)

    op.create_table('schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'time_slot_id', name='uq_class_slot_assignment'),
    sa.UniqueConstraint('teacher_id', 'time_slot_id', name='uq_teacher_slot_assignment')
    )
    with op.batch_alter_table('schedule_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_entries_id'), ['id'], unique=False)

    op.create_table('teacher_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'time_slot_id', name='uq_teacher_availability')
    )
    with op.batch_alter_table('teacher_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_availability_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_availability_id'))

    op.drop_table('teacher_availability')
    with op.batch_alter_table('schedule_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_entries_id'))

    op.drop_table('schedule_entries')
    with op.batch_alter_table('course_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_requirements_id'))

    op.drop_table('course_requirements')
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_slots_id'))

    op.drop_table('time_slots')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_id'))

    op.drop_table('teachers')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('class_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_groups_id'))

    op.drop_table('class_groups')
    # ### end Alembic commands ###
